no change     /home/wangxinrong/miniconda3/condabin/conda
no change     /home/wangxinrong/miniconda3/bin/conda
no change     /home/wangxinrong/miniconda3/bin/conda-env
no change     /home/wangxinrong/miniconda3/bin/activate
no change     /home/wangxinrong/miniconda3/bin/deactivate
no change     /home/wangxinrong/miniconda3/etc/profile.d/conda.sh
no change     /home/wangxinrong/miniconda3/etc/fish/conf.d/conda.fish
no change     /home/wangxinrong/miniconda3/shell/condabin/Conda.psm1
no change     /home/wangxinrong/miniconda3/shell/condabin/conda-hook.ps1
no change     /home/wangxinrong/miniconda3/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /home/wangxinrong/miniconda3/etc/profile.d/conda.csh
no change     /home/wangxinrong/.bashrc
No action taken.

CondaError: Run 'conda init' before 'conda activate'

[2025-01-02 17:15:46,187] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
W0102 17:15:47.582000 1186119 site-packages/torch/distributed/run.py:793] 
W0102 17:15:47.582000 1186119 site-packages/torch/distributed/run.py:793] *****************************************
W0102 17:15:47.582000 1186119 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0102 17:15:47.582000 1186119 site-packages/torch/distributed/run.py:793] *****************************************
[2025-01-02 17:15:51,418] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-01-02 17:15:51,449] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-01-02 17:15:51,449] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-01-02 17:15:51,710] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-01-02 17:15:51,715] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-01-02 17:15:51,724] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-01-02 17:15:51,735] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-01-02 17:15:51,833] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-01-02 17:15:52,794] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-01-02 17:15:52,818] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-01-02 17:15:52,866] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-01-02 17:15:53,088] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-01-02 17:15:53,090] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-01-02 17:15:53,090] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Encountered exception while importing tiktoken: No module named 'tiktoken'
[rank5]: Traceback (most recent call last):
[rank5]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 747, in <module>
[rank5]:     main(args)
[rank5]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 513, in main
[rank5]:     tokenizer = AutoTokenizer.from_pretrained(
[rank5]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 902, in from_pretrained
[rank5]:     tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
[rank5]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 541, in get_class_from_dynamic_module
[rank5]:     final_module = get_cached_module_file(
[rank5]:                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 366, in get_cached_module_file
[rank5]:     modules_needed = check_imports(resolved_module_file)
[rank5]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 198, in check_imports
[rank5]:     raise ImportError(
[rank5]: ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run `pip install tiktoken`
Encountered exception while importing tiktoken: No module named 'tiktoken'
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 747, in <module>
[rank2]:     main(args)
[rank2]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 513, in main
[rank2]:     tokenizer = AutoTokenizer.from_pretrained(
[rank2]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 902, in from_pretrained
[rank2]:     tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
[rank2]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 541, in get_class_from_dynamic_module
[rank2]:     final_module = get_cached_module_file(
[rank2]:                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 366, in get_cached_module_file
[rank2]:     modules_needed = check_imports(resolved_module_file)
[rank2]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 198, in check_imports
[rank2]:     raise ImportError(
[rank2]: ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run `pip install tiktoken`
[2025-01-02 17:15:53,112] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-01-02 17:15:53,161] [INFO] [comm.py:652:init_distributed] cdb=None
Encountered exception while importing tiktoken: No module named 'tiktoken'
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 747, in <module>
[rank1]:     main(args)
[rank1]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 513, in main
[rank1]:     tokenizer = AutoTokenizer.from_pretrained(
[rank1]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 902, in from_pretrained
[rank1]:     tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
[rank1]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 541, in get_class_from_dynamic_module
[rank1]:     final_module = get_cached_module_file(
[rank1]:                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 366, in get_cached_module_file
[rank1]:     modules_needed = check_imports(resolved_module_file)
[rank1]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 198, in check_imports
[rank1]:     raise ImportError(
[rank1]: ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run `pip install tiktoken`
[2025-01-02 17:15:53,209] [INFO] [comm.py:652:init_distributed] cdb=None
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
{'model_name_or_path': '/home/wangxinrong/.cache/modelscope/hub/ZhipuAI/glm-4-9b-chat', 'tokenizer_name_or_path': '/home/wangxinrong/.cache/modelscope/hub/ZhipuAI/glm-4-9b-chat', 'model_dir': '/share/finetune/ppo_paper_final_new/_models_outputs_sft/zhouyi_glm4_sft/', 'train_file': 'data/my_data/zhouyi_train.json', 'test_file': 'data/my_data/zhouyi_test.json', 'batch_size': 1, 'eval_batch_size': 1, 'n_epochs': 40, 'num_workers': 8, 'learning_rate': 1e-05, 'weight_decay': 0.0, 'warmup_step': None, 'clip_grad_norm': 1.0, 'evaluating_epoch_freq': 1, 'logging_epoch_freq': 1, 'saving_epoch_freq': 1, 'evaluating_step_freq': None, 'logging_step_freq': 10, 'saving_step_freq': None, 'seed': 42, 'max_input_length': 512, 'max_gen_length': 512, 'gradient_accumulation_steps': 2, 'keep_num_ckpt': 1, 'wandb_log': False, 'wandb_project': 'ReFT', 'wandb_run_name': 'zhouyi_glm4_sft', 'engine': 'nl'}
{
  "model_name_or_path": "/home/wangxinrong/.cache/modelscope/hub/ZhipuAI/glm-4-9b-chat",
  "tokenizer_name_or_path": "/home/wangxinrong/.cache/modelscope/hub/ZhipuAI/glm-4-9b-chat",
  "model_dir": "/share/finetune/ppo_paper_final_new/_models_outputs_sft/zhouyi_glm4_sft/",
  "train_file": "data/my_data/zhouyi_train.json",
  "test_file": "data/my_data/zhouyi_test.json",
  "batch_size": 1,
  "eval_batch_size": 1,
  "n_epochs": 40,
  "num_workers": 8,
  "learning_rate": 1e-05,
  "weight_decay": 0.0,
  "warmup_step": null,
  "clip_grad_norm": 1.0,
  "evaluating_epoch_freq": 1,
  "logging_epoch_freq": 1,
  "saving_epoch_freq": 1,
  "evaluating_step_freq": null,
  "logging_step_freq": 10,
  "saving_step_freq": null,
  "seed": 42,
  "max_input_length": 512,
  "max_gen_length": 512,
  "gradient_accumulation_steps": 2,
  "keep_num_ckpt": 1,
  "wandb_log": false,
  "wandb_project": "ReFT",
  "wandb_run_name": "zhouyi_glm4_sft",
  "engine": "nl"
}
Encountered exception while importing tiktoken: No module named 'tiktoken'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 747, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 513, in main
[rank0]:     tokenizer = AutoTokenizer.from_pretrained(
[rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 902, in from_pretrained
[rank0]:     tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 541, in get_class_from_dynamic_module
[rank0]:     final_module = get_cached_module_file(
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 366, in get_cached_module_file
[rank0]:     modules_needed = check_imports(resolved_module_file)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 198, in check_imports
[rank0]:     raise ImportError(
[rank0]: ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run `pip install tiktoken`
Encountered exception while importing tiktoken: No module named 'tiktoken'
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 747, in <module>
[rank3]:     main(args)
[rank3]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 513, in main
[rank3]:     tokenizer = AutoTokenizer.from_pretrained(
[rank3]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 902, in from_pretrained
[rank3]:     tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
[rank3]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 541, in get_class_from_dynamic_module
[rank3]:     final_module = get_cached_module_file(
[rank3]:                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 366, in get_cached_module_file
[rank3]:     modules_needed = check_imports(resolved_module_file)
[rank3]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 198, in check_imports
[rank3]:     raise ImportError(
[rank3]: ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run `pip install tiktoken`
Encountered exception while importing tiktoken: No module named 'tiktoken'
[rank6]: Traceback (most recent call last):
[rank6]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 747, in <module>
[rank6]:     main(args)
[rank6]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 513, in main
[rank6]:     tokenizer = AutoTokenizer.from_pretrained(
[rank6]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 902, in from_pretrained
[rank6]:     tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
[rank6]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 541, in get_class_from_dynamic_module
[rank6]:     final_module = get_cached_module_file(
[rank6]:                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 366, in get_cached_module_file
[rank6]:     modules_needed = check_imports(resolved_module_file)
[rank6]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 198, in check_imports
[rank6]:     raise ImportError(
[rank6]: ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run `pip install tiktoken`
Encountered exception while importing tiktoken: No module named 'tiktoken'
[rank4]: Traceback (most recent call last):
[rank4]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 747, in <module>
[rank4]:     main(args)
[rank4]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 513, in main
[rank4]:     tokenizer = AutoTokenizer.from_pretrained(
[rank4]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 902, in from_pretrained
[rank4]:     tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
[rank4]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 541, in get_class_from_dynamic_module
[rank4]:     final_module = get_cached_module_file(
[rank4]:                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 366, in get_cached_module_file
[rank4]:     modules_needed = check_imports(resolved_module_file)
[rank4]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 198, in check_imports
[rank4]:     raise ImportError(
[rank4]: ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run `pip install tiktoken`
Encountered exception while importing tiktoken: No module named 'tiktoken'
[rank7]: Traceback (most recent call last):
[rank7]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 747, in <module>
[rank7]:     main(args)
[rank7]:   File "/home/wangxinrong/workspace/reft/divination/mwp_ReFT/train_sft_model.py", line 513, in main
[rank7]:     tokenizer = AutoTokenizer.from_pretrained(
[rank7]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 902, in from_pretrained
[rank7]:     tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
[rank7]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 541, in get_class_from_dynamic_module
[rank7]:     final_module = get_cached_module_file(
[rank7]:                    ^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 366, in get_cached_module_file
[rank7]:     modules_needed = check_imports(resolved_module_file)
[rank7]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/transformers/dynamic_module_utils.py", line 198, in check_imports
[rank7]:     raise ImportError(
[rank7]: ImportError: This modeling file requires the following packages that were not found in your environment: tiktoken. Run `pip install tiktoken`
[rank0]:[W102 17:15:53.848283096 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W0102 17:15:54.208000 1186119 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1186289 closing signal SIGTERM
W0102 17:15:54.210000 1186119 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1186290 closing signal SIGTERM
W0102 17:15:54.211000 1186119 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1186292 closing signal SIGTERM
W0102 17:15:54.213000 1186119 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1186294 closing signal SIGTERM
W0102 17:15:54.214000 1186119 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1186295 closing signal SIGTERM
W0102 17:15:54.215000 1186119 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1186297 closing signal SIGTERM
W0102 17:15:54.216000 1186119 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1186300 closing signal SIGTERM
E0102 17:15:54.447000 1186119 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 2 (pid: 1186291) of binary: /home/wangxinrong/miniconda3/envs/cuda-12.2/bin/python3.12
Traceback (most recent call last):
  File "/home/wangxinrong/miniconda3/envs/cuda-12.2/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1153, in launch_command
    deepspeed_launcher(args)
  File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/accelerate/commands/launch.py", line 846, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wangxinrong/miniconda3/envs/cuda-12.2/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_sft_model.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-01-02_17:15:54
  host      : HS-DSS8440-009
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1186291)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
